### PR TITLE
fix(error): implement reset event

### LINKED ISSUE #8: Exception when reaching last image, and trying to load the next
Thanks for this great module! It's one of the centerpieces of my magic mirror setup, and I really appreciate it!

I'm running into the following error:

**Error description:**

When the module reaches the last of the images in the directory, and attempts to load the next, it will stay on the last image indefinitely. Looking at the logs, an exception is thrown.

**Expected behavior:**

The module should loop and start from the first image in the directory again.

**Details:**

Here's the exception:

> 
> 0|mm       | [2024-11-26 09:26:31.888] [ERROR] TypeError: Cannot read properties of undefined (reading 'name')
> 0|mm       |     at Class.dirChangeAlgo (/home/pi/MagicMirror/modules/MMM-FTP-image/node_helper.js:71:72)
> 0|mm       |     at module.exports.<anonymous> (/home/pi/MagicMirror/modules/MMM-FTP-image/node_helper.js:49:11)
> 0|mm       |     at module.exports.emit (node:events:519:28)
> 0|mm       |     at Object.reentry [as cb] (/home/pi/MagicMirror/modules/MMM-FTP-image/node_modules/ftp/lib/connection.js:238:14)
> 0|mm       |     at Parser.<anonymous> (/home/pi/MagicMirror/modules/MMM-FTP-image/node_modules/ftp/lib/connection.js:117:20)
> 0|mm       |     at Parser.emit (node:events:519:28)
> 0|mm       |     at Parser._write (/home/pi/MagicMirror/modules/MMM-FTP-image/node_modules/ftp/lib/parser.js:59:10)
> 0|mm       |     at writeOrBuffer (node:internal/streams/writable:564:12)
> 0|mm       |     at _write (node:internal/streams/writable:493:10)
> 0|mm       |     at Writable.write (node:internal/streams/writable:502:10)
> 0|mm       |     at Socket.ondata (/home/pi/MagicMirror/modules/MMM-FTP-image/node_modules/ftp/lib/connection.js:273:20)
> 0|mm       |     at Socket.emit (node:events:519:28)
> 0|mm       |     at addChunk (node:internal/streams/readable:559:12)
> 0|mm       |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
> 0|mm       |     at Readable.push (node:internal/streams/readable:390:5)
> 0|mm       |     at TCP.onStreamRead (node:internal/stream_base_commons:191:23)

And here's my config:

>     {
>         module: 'MMM-FTP-image',
>         position: 'middle_center',
>         config: {
>             // FTP server configuration
>             port: 21,
>             user: '<user>',
>             host: '<server>,
>             password: '<password>',
> 
>             // Display configuration
>             opacity: 0.4,
>             height: '100%',
>             imgChangeInterval: 10000,
> 
>             // FTP directory configuration
>             defaultDirPath: '</path/to/images>',
>             dirPathsAuthorized: ['</path/to/images>'],
>         },
>     },

Thank you for your time!

### PR DESCRIPTION
**Pull request by jboucly**
## Issues

See ➡️ #8 

## Description

Bug identified in the image search when changing directory. Sometimes, for an unknown reason (would deserve further investigation) the `ftp` package does not find the next file that must be loaded and therefore returns an error.

## Resolution 

For fix this bug, i implement `RESET` event. It is trigger when the package `ftp` return an error. 
The `RESET` event, trigger the reset of module and start again to index 0.

### CODE REVIEW

File: MMM-FTP-image.js [hunk 1]
```diff
@@ -149,6 +160,7 @@ Module.register('MMM-FTP-image', {
 
 	incrementImageIndex: function () {
 		this.logMessage(`Current image index: ${this.imageDisplayedNumber}`);
+		console.log('IMG list length', this.imgNameList.length, this.imageDisplayedNumber);
```
Comment (jboucly) [inline MMM-FTP-image.js]: To delete

File: node_helper.js [hunk 2]
```diff
@@ -102,13 +102,20 @@ module.exports = NodeHelper.create({
 
 	moveDir: function (ftp, path) {
 		ftp.cwd(path, function (err) {
-			if (err) throw err;
+			if (err) {
+				console.warn('Error while moving to directory', err);
+				self.reset();
+				throw err;
```
Comment (jboucly) [inline node_helper.js:108]: Not trigger error on ftp event
